ARG sourceimage=khulnasoft/tradescope
ARG sourcetag=develop_freqai
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-tradeai.txt requirements-tradeai-rl.txt /tradescope/

RUN pip install -r requirements-tradeai-rl.txt --user --no-cache-dir
