ARG sourceimage=khulnasoft/tradescope
ARG sourcetag=develop
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-freqai.txt /tradescope/

RUN pip install -r requirements-freqai.txt --user --no-cache-dir
